-- Convert id columns to BIGINT identity columns to eliminate race conditions
-- in ID assignment and provide future-proof headroom. Previously the API used
-- SELECT COALESCE(MAX(id)+1, 0) which two concurrent requests could resolve
-- to the same value.

-- Widen primary keys and every column that references them. Postgres
-- requires foreign-key columns to share a type with the referenced column,
-- so the FK columns and the array element types must change together.
ALTER TABLE operators         ALTER COLUMN id TYPE BIGINT;
ALTER TABLE assets            ALTER COLUMN id TYPE BIGINT;
ALTER TABLE settlements       ALTER COLUMN id TYPE BIGINT;
ALTER TABLE settlements       ALTER COLUMN operator_id TYPE BIGINT;
ALTER TABLE settlements       ALTER COLUMN asset_id TYPE BIGINT;
ALTER TABLE account_balances  ALTER COLUMN asset_id TYPE BIGINT;
ALTER TABLE locked_balances   ALTER COLUMN asset_id TYPE BIGINT;
ALTER TABLE proofs            ALTER COLUMN id TYPE BIGINT;
ALTER TABLE proofs            ALTER COLUMN settlement_id TYPE BIGINT;
ALTER TABLE cross_settlements ALTER COLUMN id TYPE BIGINT;
ALTER TABLE cross_settlements ALTER COLUMN initiator_id TYPE BIGINT;
ALTER TABLE cross_settlements ALTER COLUMN participants TYPE BIGINT[];
ALTER TABLE cross_settlements ALTER COLUMN approvals TYPE BIGINT[];

-- Add identity sequences to primary keys.
ALTER TABLE operators         ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE assets            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE settlements       ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE proofs            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE cross_settlements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Advance each sequence past existing data so new inserts pick up cleanly.
SELECT setval(pg_get_serial_sequence('operators', 'id'),
              COALESCE((SELECT MAX(id) FROM operators), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('assets', 'id'),
              COALESCE((SELECT MAX(id) FROM assets), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('settlements', 'id'),
              COALESCE((SELECT MAX(id) FROM settlements), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('proofs', 'id'),
              COALESCE((SELECT MAX(id) FROM proofs), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('cross_settlements', 'id'),
              COALESCE((SELECT MAX(id) FROM cross_settlements), 0) + 1, false);
