-- Convert id columns to identity columns to eliminate race conditions in
-- ID assignment. Previously the API used SELECT COALESCE(MAX(id)+1, 0) which
-- two concurrent requests could resolve to the same value.

ALTER TABLE operators         ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE assets            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE settlements       ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE proofs            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE cross_settlements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('operators', 'id'),
              COALESCE((SELECT MAX(id) FROM operators), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('assets', 'id'),
              COALESCE((SELECT MAX(id) FROM assets), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('settlements', 'id'),
              COALESCE((SELECT MAX(id) FROM settlements), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('proofs', 'id'),
              COALESCE((SELECT MAX(id) FROM proofs), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('cross_settlements', 'id'),
              COALESCE((SELECT MAX(id) FROM cross_settlements), 0) + 1, false);
